### ISSUE TITLE
アドオンマネージャーからインストール出来るようにしてほしい

### ISSUE THREAD

**Issue by kajikum** [R-ToS/ToS-Addon#1]
もう引退されているかもしれませんが、日本版のアドオンマネージャーでインストール出来るようになると嬉しいです。  

[JToS Addon Manager](https://github.com/JTosAddon/Tree-of-Savior-Addon-Manager)
[Wiki](https://github.com/JTosAddon/JTosAddonWiki/wiki/addon-manager)

**Comment by R-ToS** [comment]
ひえー、仕事や他のことに夢中で3か月遅くなりました！
先ほどJToS Addon Managerにリクエストしてきましたので、手順が間違ってなければ反映されると思います。
詳しいページのURL、どうもありがとうございました！

**Comment by kajikum** [comment]
全然気にせず！
対応してくれてありがとです(*ﾟ∀ﾟ)
